"""Pairwise sentence similarity utilities for two Sanskrit texts."""

from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

import numpy as np

from .embeddings import DEFAULT_MODEL_ID, TextEmbedder, TorchDTypeName
from .normalization import normalize_text
from .pipeline import resolve_segmenter
from .pairwise_run import (
    PairwiseRunResult,
    cosine_similarity_matrix as core_cosine_similarity_matrix,
    make_segments,
    run_pairwise_similarity_core,
    top_k_match_records,
)


@dataclass(slots=True)
class PairMatch:
    """One ranked sentence-pair match."""

    rank: int
    score: float
    i: int
    j: int
    sentence_a: str
    sentence_b: str


@dataclass(slots=True)
class PairwiseArtifacts:
    """Artifact paths generated by a pairwise run."""

    topk_csv: Path
    topk_jsonl: Path
    manifest_json: Path
    similarity_npy: Path | None = None


@dataclass(slots=True)
class PairwiseResult:
    """In-memory result bundle for pairwise matching."""

    matches: list[PairMatch]
    segments_a: list[str]
    segments_b: list[str]
    similarity_matrix: np.ndarray


def cosine_similarity_matrix(embeddings_a: np.ndarray, embeddings_b: np.ndarray) -> np.ndarray:
    """Compatibility wrapper around canonical cosine similarity logic."""
    return core_cosine_similarity_matrix(embeddings_a, embeddings_b)


def segment_text_to_sentences(
    text: str,
    engine: str = "dandas",
    source_format: str = "devanagari",
    split_on_single_danda: bool = False,
) -> list[str]:
    """Normalize and segment one text into sentence strings."""
    segmenter = resolve_segmenter(
        engine=engine,
        split_on_single_danda=split_on_single_danda,
    )
    normalized = normalize_text(
        text,
        source_format=source_format,
        preserve_lines=segmenter.requires_line_structure,
        transliterate=not segmenter.keep_source_script,
    )
    segmented = segmenter.segment(normalized)
    return [segment.text for segment in segmented if segment.text.strip()]


def global_top_k_matches(
    matrix: np.ndarray,
    sentences_a: list[str],
    sentences_b: list[str],
    k: int,
) -> list[PairMatch]:
    """Return globally highest-scoring i,j sentence pairs."""
    match_records = top_k_match_records(matrix, make_segments(sentences_a), make_segments(sentences_b), k)
    return [
        PairMatch(
            rank=match.rank,
            score=match.score,
            i=match.segment_a.index,
            j=match.segment_b.index,
            sentence_a=match.segment_a.text,
            sentence_b=match.segment_b.text,
        )
        for match in match_records
    ]


def run_pairwise_similarity(
    text_a: str,
    text_b: str,
    output_dir: str | Path,
    *,
    engine: str = "dandas",
    source_format: str = "devanagari",
    split_on_single_danda: bool = False,
    model_id: str = DEFAULT_MODEL_ID,
    batch_size: int = 8,
    device: str = "auto",
    embedding_progress: Literal["off", "batch", "sentence"] = "off",
    torch_dtype: TorchDTypeName | None = None,
    device_map: str | dict[str, int | str] | None = None,
    load_in_8bit: bool = False,
    low_cpu_mem_usage: bool | None = None,
    top_k: int = 100,
    save_similarity_npy: bool = False,
) -> PairwiseArtifacts:
    """Run segment -> embed -> similarity -> global top-k for two texts."""
    sentences_a = segment_text_to_sentences(
        text_a,
        engine=engine,
        source_format=source_format,
        split_on_single_danda=split_on_single_danda,
    )
    sentences_b = segment_text_to_sentences(
        text_b,
        engine=engine,
        source_format=source_format,
        split_on_single_danda=split_on_single_danda,
    )

    embedder = TextEmbedder(
        model_id=model_id,
        batch_size=batch_size,
        normalize_embeddings=True,
        device=device,
        embedding_progress=embedding_progress,
        torch_dtype=torch_dtype,
        device_map=device_map,
        load_in_8bit=load_in_8bit,
        low_cpu_mem_usage=low_cpu_mem_usage,
    )
    embeddings_a = embedder.encode_queries(sentences_a).embeddings
    embeddings_b = embedder.encode_corpus(sentences_b).embeddings
    result = run_pairwise_similarity_core(
        make_segments(sentences_a),
        embeddings_a,
        make_segments(sentences_b),
        embeddings_b,
        top_k=top_k,
    )
    matrix = result.similarity_matrix
    matches = _compatibility_matches(result)

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    topk_csv = output_dir / "topk_pairs.csv"
    topk_jsonl = output_dir / "topk_pairs.jsonl"
    manifest_json = output_dir / "run_manifest.json"
    write_topk_csv(matches, topk_csv)
    write_topk_jsonl(matches, topk_jsonl)

    similarity_npy: Path | None = None
    if save_similarity_npy:
        similarity_npy = output_dir / "similarity_matrix.npy"
        np.save(similarity_npy, matrix)

    manifest = {
        "engine": engine,
        "source_format": source_format,
        "model_id": model_id,
        "device": device,
        "batch_size": batch_size,
        "top_k_requested": top_k,
        "top_k_returned": len(matches),
        "embedding_progress": embedding_progress,
        "segment_count_a": len(sentences_a),
        "segment_count_b": len(sentences_b),
        "matrix_shape": list(matrix.shape),
        "max_score": result.metrics.max_score,
        "mean_score": result.metrics.mean_score,
        "median_score": result.metrics.median_score,
        "p95_score": result.metrics.p95_score,
        "mean_best_a_to_b": result.metrics.mean_best_a_to_b,
        "mean_best_b_to_a": result.metrics.mean_best_b_to_a,
        "topk_csv": str(topk_csv),
        "topk_jsonl": str(topk_jsonl),
        "similarity_npy": str(similarity_npy) if similarity_npy else None,
    }
    manifest_json.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    return PairwiseArtifacts(
        topk_csv=topk_csv,
        topk_jsonl=topk_jsonl,
        manifest_json=manifest_json,
        similarity_npy=similarity_npy,
    )


def write_topk_csv(matches: list[PairMatch], output_path: str | Path) -> Path:
    """Write ranked matches to CSV."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["rank", "score", "i", "j", "sentence_a", "sentence_b"]
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for match in matches:
            writer.writerow(asdict(match))
    return output_path


def write_topk_jsonl(matches: list[PairMatch], output_path: str | Path) -> Path:
    """Write ranked matches to JSONL."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        for match in matches:
            handle.write(json.dumps(asdict(match), ensure_ascii=False))
            handle.write("\n")
    return output_path


def _compatibility_matches(result: PairwiseRunResult) -> list[PairMatch]:
    return [
        PairMatch(
            rank=match.rank,
            score=match.score,
            i=match.segment_a.index,
            j=match.segment_b.index,
            sentence_a=match.segment_a.text,
            sentence_b=match.segment_b.text,
        )
        for match in result.matches
    ]
